### ISSUE TITLE
Offline checks in meta-security layer

### ISSUE THREAD

**Issue by ipuustin** [01org/meta-security-isafw#11]
Meta-security layer at http://git.yoctoproject.org/cgit/cgit.cgi/meta-security contains several scripts for offline security checks (see package redhat-security). Could you consider adding some of those scripts to the isafw layer or implementing corresponding functionality in existing checks? Thanks!

**Comment by ereshetova** [comment]
Checks for executable stack are added in this commit: 74bcd9d925140208742bd90a0c183fd86e20f341

**Comment by ereshetova** [comment]
Calling setuid/setgid variants without calling initgroups/setgroups addressed in commit: 40716d0ee9f055ad01ddc58d01c0c22191da67f8

**Comment by ereshetova** [comment]
Both commits are merged now. I am closing the issue. Rest of offline security checks are either already present in meta-security-isafw or not really applicable for the usecase in mind.
