### ISSUE TITLE
Exception: IndexError: list index out of range

### ISSUE THREAD

**Issue by embeddedgeeks** [01org/meta-security-isafw#29]
Hello,
used both jethro and master baranches, I'm getting all the time this error :
`The stack trace of python calls that resulted in this exception/failure was:
File: 'analyse_image', lineno: 65, function: <module>
     0061:    bb.debug(1, 'do image analysis on %s' % rootfsdir)
     0062:    imageSecurityAnalyser.process_filesystem(fs)
     0063:
     0064:
 **\* 0065:analyse_image(d)
     0066:
File: 'analyse_image', lineno: 39, function: analyse_image
     0035:        isafw_config.plugin_blacklist = re.split(r'[,\s]_', blacklist)
     0036:
     0037:    imageSecurityAnalyser = isafw.ISA(isafw_config)
     0038:
 *_\* 0039:    pkglist = manifest2pkglist(d)
     0040:
     0041:    kernelconf = d.getVar('STAGING_KERNEL_BUILDDIR', True) + "/.config"
     0042:
     0043:    kernel = isafw.ISA_kernel()
File: 'isafw.bbclass', lineno: 13, function: manifest2pkglist
     0009:    with open(pkglist, 'w') as foutput:
     0010:        with open(manifest_file, 'r') as finput:
     0011:            for line in finput:
     0012:                items = line.split()
 **\* 0013:                foutput.write(items[0] + " " + items[2] + "\n")
     0014:
     0015:    return pkglist
     0016:
     0017:
Exception: IndexError: list index out of range

ERROR: Function failed: analyse_image`

**Comment by ereshetova** [comment]
Do you use any plugin_blacklist? If yes, can you provide your values that I can reproduce the first error.
For the second could you print and paste to me the value of "items"? 

I will try to address this asap after I get to reproduce it.

**Comment by ereshetova** [comment]
Anyway, second issue should be fixed here: c7559f9b4f557c75ad79543a01b13472b481aaab
For the first issue I still don't understand what goes wrongly. Could you please give your blacklist value?

**Comment by embeddedgeeks** [comment]
The plugin variables are not set :
ISAFW_PLUGINS_WHITELIST ?= ""
ISAFW_PLUGINS_BLACKLIST ?= ""

**Comment by embeddedgeeks** [comment]
Ok thanks for the commit I think it fixes the issue :-)

**Comment by ereshetova** [comment]
Can you confirm that you are not seeing any issues then anymore?

**Comment by embeddedgeeks** [comment]
I can confirm that the build error is fixed but I noticed that the in report folder :
build / tmp / log / isafw-report_20160223130750 /
the two files :
cve-report_20160223130750.csv   0 B  
cve-report_20160223130750.html  0 B
are empty !!!

**Comment by ereshetova** [comment]
that is probably not related to the previous issues in anyway. Do you use proxy? cve plugin needs internet connection for it to work.

**Comment by embeddedgeeks** [comment]
yes I'm using a http proxy, but it's correctly set because I can download all packages yocto is using.
is cve plugin also uses a standard http connection ?

**Comment by ereshetova** [comment]
when you run the build, can you check from debug output the value of isafw_config.proxy to make sure it is passed correctly in your environment to isafw: 

https://github.com/01org/meta-security-isafw/blob/master/classes/isafw.bbclass#L196

also, when build is ongoing and you see do_analyse_source tasks being executed per each recipe, do you see *.faux file created (and continuously populated with package names) in the report dir (same place as cve report will be created later)?

**Comment by embeddedgeeks** [comment]
I did a build 3xtimes, and only once I got cve-report files populated, I don't think it's a proxy issue.
I'm having daily build without using a local download cache and so far never had problem with the proxy.
It should be something else.
the .faux are created and pouplated but somehow the report are empty though !

**Comment by ereshetova** [comment]
Ok, so if your faux file is fine and cve files are empty but not always... hm really weird. How do you run your build? Bitbake target_image? Wonder if you can tell me the exact sequence that I can reproduce

**Comment by embeddedgeeks** [comment]
I verified your suggestion :
DEBUG: isafw: proxy is http://myproxy.example:1243
DEBUG: isafw: process reports

**Comment by embeddedgeeks** [comment]
I'm using a yocto jethro based branch in combination with meta-security-isafw (master branch where  you introduced the fix today of List Index).
I'm using bitbake example-image for building, and INHERIT += "isafw" set in my local.conf

**Comment by ereshetova** [comment]
So, you are not using any OE-core provided images? Then it would be very hard for me to reproduce. Can you try to build core-image-minimal for example to test that there are no issues with it on your side.

**Comment by ereshetova** [comment]
Actually the only way for me to get the cve reports empty given that the faux file is correct is problems with connectivity. For example, I am normally working behind proxy and have it configured, but if I worked not behind proxy, but still pass proxy info to the layer, I get cve reports empty and these messages in the shell:

Update of db forced
Failed to fetch http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.meta
DB update failure
Update of db forced
Failed to fetch http://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.meta
DB update failure

You don't observe anything like this?

**Comment by ereshetova** [comment]
Actually I have come across the same issue (empty cve reports) now in our CI. Debugging this seems to reveal this output from cve-check-tool:

Update of db forced 
Unable to list modules: No such file or directory 
Cannot find any packaging plugins on this system. 

I am taking this up to cve-check-tool maintainer, smth has probably changed there.

**Comment by ereshetova** [comment]
Yes, so it was an issue with cve-check-tool. This commit 0ca0f40b50630a738123e0889b7a64ebc6ebeda6 upgrades to its last version and at least on my side issue is fully gone. Please test on your side.

**Comment by ereshetova** [comment]
I am closing this since I believe the issue is resolved. Please reopen if it isn’t the case for you.
