### ISSUE TITLE
Make execution of plugins configurable.

### ISSUE THREAD

**Issue by kad** [01org/meta-security-isafw#3]
Right now, isafw loads and executes all available plugins at the time.
This might be not desired by some developers. e.g. some would be interested in subset of checks.
To improve situation, we need to implement two lists: whitelist and blacklist for plugins.

Algorithm during plugin loading should be something like that:

``` python

for plugin in iterate_over_available_plugins():
    if whitelist and plugin not in whitelist:
        continue
    if blacklist and plugin in blacklist:
        continue
    load_plugin(plugin)
```

**Comment by ereshetova** [comment]
Implemented in cfb50ba8817b725b6b986a25f1e1c9e457c0e035

Example of configuring: 

ISAFW_PLUGINS_WHITELIST ?= "ISA_CVEChecker,ISA_LicenseChecker,ISA_CFChecker,ISA_KernelChecker,ISA_FSChecker"
ISAFW_PLUGINS_BLACKLIST ?= "ISA_CVEChecker"

Tested to work.

Please let me know if you are ok with implementation and I will make a merge to master.

**Comment by kad** [comment]
please use 

``` python
xxx_list = re.split("\s?,\s?", d.getVar(......))
```

this would be more safe way to detect names of plugins in case they have common prefix.

**Comment by ereshetova** [comment]
fixed and merged to master
