### ISSUE TITLE
CVE checker: report fatal errors

### ISSUE THREAD

**Issue by pohly** [01org/meta-security-isafw#60]
Currently the CVE checks fail with:

```
<testsuite name="CVE_Plugin" tests="3"><testcase classname="ISA_CVEChecker" name="Update of db forced"/><testcase classname="ISA_CVEChecker" name="Failed to fetch https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.meta"/><testcase classname="ISA_CVEChecker" name="DB update failure"/></testsuite>
```

However, that is not detected as error by Jenkins:
https://ostroproject.org/jenkins/view/Code-Analysis/job/code_isafw_reports/31/

Build #462 in that report had the error above but gets shown as "blue" = everything okay.

**Comment by pohly** [comment]
Also or in addition, the actual CVE check needs to be fixed. This is even more important.

**Comment by terriko** [comment]
Have you reported this in the CVE check tool bug tracker? 
Link: https://github.com/ikeydoherty/cve-check-tool/issues 
(I didn't see it but I don't know if it was reported internal-only)

**Comment by terriko** [comment]
Also, I asked Mike D and it sounds like the Clear team is also seeing this, so hopefully it's on their radar already.

**Comment by ereshetova** [comment]
@pohly, I made plugin to report failures from cve-check-tool as failures for jenkins: https://github.com/01org/meta-security-isafw/commit/5aea47ea448c9ffddfc5bb7479684dd1dda5372a The actual fixing of cve-check-tool itself is next task

**Comment by ereshetova** [comment]
@pohly I think we can close this issue: plugin reports errors correctly and now even works :)

**Comment by pohly** [comment]
Yes, it works now.
