### ISSUE TITLE
CFA: excessive memory usage

### ISSUE THREAD

**Issue by pohly** [01org/meta-security-isafw#62]
In private builds (i.e. can't link to them here) we see excessive memory usage (>50GB) in the bitbake workers which (most likely) executes the CFA process_filesystem() code. Builds never completed without getting killed by the kernel OOM killer and we haven't had time to investigate, so this might be both a problem with the code or the image that is getting analyzed.

However, even if the image is just producing too many reports, the code should be able to handle that without this excessive memory usage.

**Comment by ereshetova** [comment]
Should be much better with this commit: https://github.com/01org/meta-security-isafw/commit/2e05daeb5a64035150301b11a952234152ce7382

**Comment by ereshetova** [comment]
@pohly, do you still see this issue now?

**Comment by pohly** [comment]
I haven't enabled cfa checks again. Let me do that now and then we'll see whether it really works better where it previously failed.

**Comment by ereshetova** [comment]
I am closing this since we have seen the issue anymore
