### ISSUE TITLE
Checksum on external file changed

### ISSUE THREAD

**Issue by pltxtra** [01org/meta-security-isafw#69]
https://github.com/01org/meta-security-isafw/blob/master/recipes-devtools/checksec/checksec_1.5.bb

This recipe downloads the checksec.sh script from a known location. The file format of that has changed recently from UNIX to DOS. This means that the checksum is now different and this recipe will fail.

**Comment by ereshetova** [comment]
Thanks for the note! I will update the checksum!

**Comment by ereshetova** [comment]
fix merged in https://github.com/01org/meta-security-isafw/pull/73 and https://github.com/01org/meta-security-isafw/pull/74
